apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: google/cloud-sdk:slim
              env:
                - name: PGHOST
                  value: postgres-svc
                - name: PGPORT
                  value: "5432"
                - name: PGDATABASE
                  value: postgres
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: password
                - name: GCS_BUCKET
                  value: "YOUR-GCS-BUCKET-NAME"

              command:
                - /bin/sh
                - -c
                - |
                  apt-get update
                  apt-get install -y postgresql-client
                  DATE=$(date +%Y-%m-%d-%H-%M)
                  pg_dump > /tmp/todo-$DATE.sql
                  gcloud storage cp /tmp/todo-$DATE.sql gs://$GCS_BUCKET/