apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/configmap.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml

images:
  - name: log-writer
    newName: log-writer
    newTag: latest
  - name: log-reader
    newName: log-reader
    newTag: latest