apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-writer
          image: log-writer:1.10
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: log-reader
          image: log-reader:2.6
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:3000/pingpong"
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-data
              mountPath: /data
            - name: config-volume
              mountPath: /data/information.txt
              subPath: information.txt
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: config-volume
          configMap:
            name: log-output-config
            