apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-writer
          image: log-writer:1.10
          volumeMounts:
            - name: shared-data
              mountPath: /data

        - name: log-reader
          image: log-reader:1.10
          volumeMounts:
            - name: shared-data
              mountPath: /data

      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc