apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - broadcaster.yaml
  - backup-cronjob.yaml