apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.0
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-db-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: todo-postgres-storage
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: todo-postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
