apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-random-wiki
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-random-wiki
              image: curlimages/curl:8.10.1
              command:
                - sh
                - -c
                - |
                  URL=$(curl -s -L -o /dev/null -w '%{url_effective}' https://en.wikipedia.org/wiki/Special:Random)
                  curl -X POST http://todo-backend-svc:3000/todos -H "Content-Type: application/json" -d "{\"text\":\"Read $URL\"}"
          restartPolicy: Never
